' Gambas module file

Export
Create Static
Public RADIVATE As Collection
Public USER_DATA As Collection
Public SHOW_USER As Boolean
Public Sub PrintValidateData()
  

  Dim VALIDATE_ID As String
  Dim DWDATE As String
  
  DWDATE = Replace(Request.Get["validate"], Right$(Request.Get["validate"], -8), "")
  
  If Exist(Global.WHEREIS_SITE_ROOT & "/ValidDB/" & DWDATE & "/" & Right$(Request.Get["validate"], -8) & ".json") = True Then
    RADIVATE = JSON.Decode(File.Load(Global.WHEREIS_SITE_ROOT & "/ValidDB/" & DWDATE & "/" & Right$(Request.Get["validate"], -8) & ".json"))
        
        If Error Then
            Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & "/inex.r?fail")
        Endif
    
    VALIDATE_ID = Request.Get["validate"]
  

  MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP & "/inex.r?validate=" & Request.Get["validate"]
  MBrand.Brand_TEXT = RADIVATE["CPUID"]["BRAND_STR"]
  If IsNull(RADIVATE["SUBMITED_BY"]) = False Then
    If Exist(Global.WHEREIS_SITE_ROOT & "/Users/" & RADIVATE["SUBMITED_BY"] & "") Then
      USER_DATA = JSON.Decode(File.Load(Global.WHEREIS_SITE_ROOT & "/Users/" & RADIVATE["SUBMITED_BY"] & "/Data.json"))
      SHOW_USER = True
    Else
      SHOW_USER = False
    Endif
  Endif
  
  If Request.Get.Exist("download") = True Then
    Response.AddHeader("Content-Disposition", "attachment; filename=" & DWDATE & Right$(Request.Get["validate"], -8) & ".png")
    Response.SendFile("" & Global.WHEREIS_SITE_ROOT & "" "/ValidScr/" & DWDATE & "/" & Right$(Request.Get["validate"], -8) & ".png", "image/png")
  Endif
  Response.Begin
  WValidate.Render
  Response.End
  Else
      Response.Begin
      Errors.Valid_Not_Found()
      Response.End
  Endif

End
