' Gambas module file

Public Sub Main()
Settings["W/w"] = "ggggg"
If CGI["HTTP_ACCEPT_LANGUAGE"] Like "*ru*" Then
  System.Language = "ru_RU.UTF-8"
Endif
If CGI["HTTP_ACCEPT_LANGUAGE"] Like "*pl*" Then
  System.Language = "pl_PL.UTF-8"
Endif
If CGI["HTTP_ACCEPT_LANGUAGE"] Like "*fr*" Then
  System.Language = "fr_FR.UTF-8"
Endif

If Request.Get["js"] = "whcookies.js" Then
  WCookies.Render
Else If Request.Get.Exist("signin") = True Then
  Signs.Sign_in()
Else If Request.Get.Exist("updprofile") = True Then
  CHGProfileDetails.CHProf()
Else If Request.Get.Exist("page") = True Then
  Page.Pages()
Else If Request.Post.Exist("uploadfile") = True Then
  Upload.SendFileToServer()
Else If Request.Get.Exist("validate") = True Then
  MValidate.PrintValidateData()
Else If Request.Get.Exist("fail") = True Then
  PrintFail()
Else If Request.Get.Exist("added") = True Then
  MLatestAdded.Added()
Else If Request.Get.Exist("signup") = True Then
  Signup.Signup()
Else If Request.Get.Exist("login") = True Then
  login.Sign()
Else If Request.Get.Exist("register") = True Then
  Register.Register()
Else If Request.Get.Exist("logout") = True Then
  logout.Remove_Cook()
Else If Request.Get.Exist("profile") = True Then
  Profile.User_Profile()
Else If Request.Get.Exist("chgapi") = True Then
  ChangeAPI_KEYS.CHKeys()
Else If Request.Get.Exist("test") = True Then
  Response.AddHeader("Content-Disposition", "attachment; filename=i-nex-0.6.4-1.1.x86_64.rpm")
  Response.SendFile("/home/michal/Pulpit/i-nex-0.6.4-1.1.x86_64.rpm", "application/x-rpm")
Else If Request.Get.Exist("delvalidate") = True Then
  DelValidate.Delete()
Else If Request.Get.Exist("query") = True Then
  MQuery.Main()
Else If Request.Get.Exist("adminpanel") = True And Usera.User_IsAdmin() = True Then
  WAdminPanel.Render
Else If Request.Get.Exist("cpudb[atom]") = True Then
  WCPUDBAtom.Render
Else
  ResponseFromServer()
Endif
End

Public Sub ResponseFromServer()
  Dim USER_DATA As Collection
  MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP & Application.Root
  MBrand.Brand_TEXT = "I-Nex - Cerbero"
  Response.Begin
    Print "<!DOCTYPE html>"
    Print "<html lang=\"en\">"
    WHead.Render
    Print "<body>"
    WNavbar.Render
    DUpload.Render
  Response.End
  
End

Public Sub PrintFail()
  
  Response.Begin
  Print File.Load("Error/NotFoundValidateID.html")
  Response.End
  
End

