' Gambas module file

Public Sub Main()
Settings["W/W"] = 11
If CGI["HTTP_ACCEPT_LANGUAGE"] Like "*ru*" Then
  System.Language = "ru_RU.UTF-8"
Endif
If CGI["HTTP_ACCEPT_LANGUAGE"] Like "*pl*" Then
  System.Language = "pl_PL.UTF-8"
Endif
If CGI["HTTP_ACCEPT_LANGUAGE"] Like "*fr*" Then
  System.Language = "fr_FR.UTF-8"
Endif

If Request.Get["js"] = "whcookies.js" Then
  WCookies.Render
Else If Request.Get.Exist("signin") = True Then
  Signs.Sign_in()
Else If Request.Get.Exist("updprofile") = True Then
  CHGProfileDetails.CHProf()
Else If Request.Get.Exist("page") = True Then
  Page.Pages()
Else If Request.Post.Exist("uploadfile") = True Then
  Upload.SendFileToServer()
Else If Request.Get.Exist("validate") = True Then
  MValidate.PrintValidateData()
Else If Request.Get.Exist("fail") = True Then
  PrintFail()
Else If Request.Get.Exist("added") = True Then
  MLatestAdded.Added()
Else If Request.Get.Exist("signup") = True Then
  Signup.Signup()
Else If Request.Get.Exist("login") = True Then
  login.Sign()
Else If Request.Get.Exist("register") = True Then
  Register.Register()
Else If Request.Get.Exist("logout") = True Then
  logout.Remove_Cook()
Else If Request.Get.Exist("profile") = True Then
  Profile.User_Profile()
Else If Request.Get.Exist("chgapi") = True Then
  ChangeAPI_KEYS.CHKeys()
Else If Request.Get.Exist("test") = True Then
  Response.AddHeader("Content-Disposition", "attachment; filename=14.0309370877082.png")
  Response.SendFile("/var/www/ValidScr/04072014/14.0309370877082.png", "image/png")
Else If Request.Get.Exist("delvalidate") = True Then
  DelValidate.Delete()
Else If Request.Get.Exist("query") = True Then
  MQuery.Main()
Else If Request.Get.Exist("padm") = True And Usera.User_IsAdmin() = True Then
  WAdminPanel.Render
Else If Request.Get.Exist("cpudb[intel]") = True Then
  Response.Begin
  WCPUDBIntel.Render
  Response.End
Else If Request.Get.Exist("cpudb[intel]edit") = True Then
 If Usera.User_Logged() = True And Usera.User_IsAdmin() = True Then
  WCPUDBIntelEdit.Render
 Else
  Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
 Endif
Else If Request.Get.Exist("cpudb[intel]view") = True Then
  Response.Begin
  WCPUDBIntelView.Render
  Response.End
Else If Request.Get.Exist("cpudb[intel]change") = True Then
  MCPUDBIntelChange.Change()
Else If Request.Get.Exist("cpudb[intel]addd") = True Then
  MCPUDBIntelAdd.Add()
Else If Request.Get.Exist("cpudb[intel]add") = True Then
  If Usera.User_Logged() = True And Usera.User_IsAdmin() = True Then
    Response.Begin
      WCPUDBIntelAdd.Render
    Response.End
  Else
    Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
  Endif
Else If Request.Get.Exist("cpudb[intel]delete") = True Then
  MCPUDBIntelDelete.Delete()
Else If Request.Get.Exist("cpudb[intel]query") = True Then
  Response.Begin
    WCPUDBIntelQuery.Render
  Response.End
Else If Request.Get.Exist("cpudb[atom]") = True Then
  Response.Begin
  WCPUDBAtom.Render
  Response.End
Else If Request.Get.Exist("cpudb[atom]edit") = True Then
 If Usera.User_Logged() = True And Usera.User_IsAdmin() = True Then
  WCPUDBAtomEdit.Render
 Else
  Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
 Endif
Else If Request.Get.Exist("cpudb[atom]view") = True Then
  Response.Begin
  WCPUDBAtomView.Render
  Response.End
Else If Request.Get.Exist("cpudb[atom]change") = True Then
  MCPUDBAtomChange.Change()
Else If Request.Get.Exist("cpudb[atom]addd") = True Then
  MCPUDBAtomAdd.Add()
Else If Request.Get.Exist("cpudb[atom]add") = True Then
  If Usera.User_Logged() = True And Usera.User_IsAdmin() = True Then
    Response.Begin
      WCPUDBAtomAdd.Render
    Response.End
  Else
    Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
  Endif
Else If Request.Get.Exist("cpudb[atom]delete") = True Then
  MCPUDBAtomDelete.Delete()
Else If Request.Get.Exist("cpudb[atom]query") = True Then
  Response.Begin
    WCPUDBAtomQuery.Render
  Response.End
Else If Request.Get.Exist("cpudb[amd]") = True Then
  Response.Begin
  WCPUDBAmd.Render
  Response.End
Else If Request.Get.Exist("cpudb[amd]edit") = True Then
 If Usera.User_Logged() = True And Usera.User_IsAdmin() = True Then
  WCPUDBAmdEdit.Render
 Else
  Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
 Endif
Else If Request.Get.Exist("cpudb[amd]view") = True Then
  Response.Begin
  WCPUDBAmdView.Render
  Response.End
Else If Request.Get.Exist("cpudb[amd]change") = True Then
  MCPUDBAmdChange.Change()
Else If Request.Get.Exist("cpudb[amd]addd") = True Then
  MCPUDBAmdAdd.Add()
Else If Request.Get.Exist("cpudb[amd]add") = True Then
  If Usera.User_Logged() = True And Usera.User_IsAdmin() = True Then
    Response.Begin
      WCPUDBAmdAdd.Render
    Response.End
  Else
    Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
  Endif
Else If Request.Get.Exist("cpudb[amd]delete") = True Then
  MCPUDBAmdDelete.Delete()
Else If Request.Get.Exist("cpudb[amd]query") = True Then
  Response.Begin
    WCPUDBAmdQuery.Render
  Response.End
Else If Request.Get.Exist("cpudb") = True Then
  Response.Begin
    WCPUDBIndex.Render
  Response.End
Else If Request.Get.Exist("downloadcount") = True Then
MDownload.Main()
Response.Redirect("http://127.0.0.1/")

Else If Request.Get.Exist("downloadcountr") = True Then
  Response.Begin
  Print MDownload.DownloadCount()
  Response.End
Else
  ResponseFromServer()
Endif
End

Public Sub ResponseFromServer()
  MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP & Application.Root
  MBrand.Brand_TEXT = "I-Nex - Cerbero"

  Response.Begin
    DUpload.Render
  Response.End
  
End

Public Sub PrintFail()
  
  Response.Begin
  Print File.Load("Error/NotFoundValidateID.html")
  Response.End
  
End

