' Gambas module file

Public Sub Pages()
  
  If Request.Get["page"] = "donate" Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP
    MBrand.Brand_TEXT = ("Donate")
    Donate.Render
  Else If Request.Get["page"] = "policy" Then
    Policy.Render
  Else If Request.Get["page"] = "translators" Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP
    MBrand.Brand_TEXT = ("Translators")
    Translators.Render
  Else If Request.Get["page"] = "team" Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP
    MBrand.Brand_TEXT = ("Team")
    Team.Render
  Else If Request.Get["page"] = "sitenews" Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP
    MBrand.Brand_TEXT = ("Team")
    MLatests_Posts.PrintLatestsPosts()
  Else
    Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
  Endif
  
End