' Gambas module file

Public Sub Pages()
  
  If Request.Get["page"] = "donate" Then
    Donate()
  Else If Request.Get["page"] = "policy" Then
    Policy.Render
  Else If Request.Get["page"] = "translators" Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP
    MBrand.Brand_TEXT = ("Translators")
    Translators.Render
  Else If Request.Get["page"] = "team" Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP
    MBrand.Brand_TEXT = ("Team")
    Team.Render
  Else If Request.Get["page"] = "sitenews" Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP
    MBrand.Brand_TEXT = ("Team")
    MLatests_Posts.PrintLatestsPosts()
  Else
    Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root)
  Endif
  
End

Public Sub Donate()
  Dim USER_DATA As Collection
    Response.Begin
    Print File.Load("Upload/Head.html")
    Print "<div class=\"navbar navbar-fixed-top\">"
    Print "   <div class=\"navbar-inner\">"
    Print "     <div class=\"container\">"
    Print "         <a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">"
    Print "           <span class=\"icon-bar\"></span>"
    Print "           <span class=\"icon-bar\"></span>"
    Print "           <span class=\"icon-bar\"></span>"
    Print "         </a>"
    Print "         <a class=\"brand\" href=\"" & Application.Root & "\">"
    Print ("           I-Nex - Cerbero")
    Print "         </a>"
    If IsNull(Request.Cookies["__ursa"]) = False Then

    If Exist(Global.WHEREIS_SITE_ROOT & "/Users/" & Request.Cookies["__ursa"] & "") Then
      USER_DATA = JSON.Decode(File.Load(Global.WHEREIS_SITE_ROOT & "/Users/" & Request.Cookies["__ursa"] & "/Data.json"))
      If USER_DATA["SECRET_KEY"] = Request.Cookies["__apix"] Then
        Print "         <div class=\"nav-collapse\">"
        Print "           <ul class=\"nav pull-right\">"
        Print "             <li class=\"dropdown\">"
        Print "                 <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">"
        Print "                   <i class=\"icon-user\"></i> "
        Print "                     " & USER_DATA["CERBERO_USERNAME"] & ""
        Print "                   <b class=\"caret\"></b>"
        Print "                 </a>"
        Print "             <ul class=\"dropdown-menu\">"
        Print "                  <li>"
        Print "                    <a href=\"" & Application.Root & "?profile\">"
        Print ("                    Profile")
        Print "                    </a>"
        Print "                  </li>"
        Print "                  <li>"
        Print "                   <a href=\"" & Application.Root & "?logout\">"
        Print ("                   Logout")
        Print "                   </a>"
        Print "                  </li>"
        Print "             </ul>"
        Print "           </li>"
        Print "         </ul>"
        Print "       </div><!--/.nav-collapse -->  "
        Print "    </div> <!-- /container -->"
        Print "</div> <!-- /navbar-inner -->"
      Else
        DUploadUserNav.Render
      Endif
    Else
      DUploadUserNav.Render
    Endif
    Else
      DUploadUserNav.Render
    Endif
    WSubnavbar.Render
    Donate.Render
  Response.End
  
End
