' Gambas module file

Public Sub User_Profile()
  Dim i, All As Integer
  Dim USER_DATA As Collection
  Dim Dict As New Collection
  Dim CPU_DATA As Collection
  Dim Element As String

  If Usera.User_Logged() = True Then
    MBrand.Brand_URL = Global.WEBSITE_ROOT_URL_HTTP & Application.Root
    MBrand.Brand_TEXT = "I-Nex - Cerbero - Profile"
    Response.Begin
    
    WProfile.Render
    
    Response.End
  Else
    Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root & "?login")
  Endif
End

Public Sub Change_Password_IN_Profile()
  Dim USER_DATA As Collection
  'Print Request.Post["email"]
  'Print Request.Post["password1"]
  'Print Request.Post["password2"]
  If IsNull(Request.Cookies["__ursa"]) = False Then
      If Exist("/var/www/Users/" & Request.Cookies["__ursa"] & "") Then
        USER_DATA = JSON.Decode(File.Load("/var/www/Users/" & Request.Cookies["__ursa"] & "/Data.json"))
        If USER_DATA["SECRET_KEY"] = Request.Cookies["__apix"] Then
        Else
          Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root & "?profile")
        Endif
      Else
        Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root & "?profile")
      Endif
  Else
    Response.Redirect(Global.WEBSITE_ROOT_URL_HTTP & Application.Root & "?profile")
  Endif
End
