' Gambas module file

' Gambas class file
Public Sub Signup()
  Dim USER_DATA As Collection
  If IsNull(Request.Cookies["__ursa"]) = False Then
      If Exist(Global.WHEREIS_SITE_ROOT & "/Users/" & Request.Cookies["__ursa"] & "") = True Then
          USER_DATA = JSON.Decode(File.Load(Global.WHEREIS_SITE_ROOT & "/Users/" & Request.Cookies["__ursa"] & "/Data.json"))
          If USER_DATA["SECRET_KEY"] = Request.Cookies["__apix"] Then
              Response.Begin
              Print File.Load("Login/head")
              Print "<div class=\"account-container\">"
              Print "   <div class=\"content clearfix\">"
              Print "           <h2>You are currently logged in.</h2>"
              Print "   </div> <!-- /content -->"
              Print "</div> <!-- /account-container -->"
              Print File.Load("Login/Footer")
          Else
            Print_Signup()
          Endif
      'Print_Signup()
      Endif
  Else
  Print_Signup()
  Endif
End

Public Sub Print_Signup()
  Response.Begin
  'Print File.Load("Signup/head")
  DSignupHead.Render
  Print "<div class=\"account-container register\">"
  
  Print "  <div class=\"content clearfix\">"
  
  Print "   <form action=\"inex.r?register\" method=\"post\">"
  
  Print "     <h1>"
  Print ("       Signup for Free Account")
  Print "     </h1>"
  Print "       <div class=\"login-fields\">"
  
  Print "           <p>"
  Print ("             Create your free account:")
  Print "           </p>"
  Print "           <div class=\"field\">"
  Print "                 <label for=\"firstname\">"
  Print ("                   User name:")
  Print "                 </label>"
  Print "                 <input type=\"text\" id=\"firstname\" name=\"firstname\" value=\"\" placeholder=\"Login\" class=\"login\" />"
  Print "           </div><!-- /field -->"
  
  If Request.Get["err1"] = "2" Then
    Print "           <div class=\"control-group\">"
    Print "             <label class=\"control-label\">Alerts</label>"
    Print "             <div class=\"controls\">"
    Print "             <div class=\"alert\">"
    Print "             <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>"
    Print "             <strong>Warning!</strong> User name is null or is to small"
    Print "           </div>"
  Endif
  
  Print ""
  Print "           <div class=\"field\">"
  Print "                 <label for=\"displayname\">"
  Print ("                   Display name:")
  Print "                 </label>"
  Print "                 <input type=\"text\" id=\"displayname\" name=\"displayname\" value=\"\" placeholder=\"Display name\" class=\"login\" />"
  Print "                 <p class=\"help-block\">Public account name. It is used in some cases.</p>"
  Print "           </div><!-- /field -->"
  
  If Request.Get["err1"] = "2" Then
    Print "           <div class=\"control-group\">"
    Print "             <label class=\"control-label\">Alerts</label>"
    Print "             <div class=\"controls\">"
    Print "             <div class=\"alert\">"
    Print "             <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>"
    Print "             <strong>Warning!</strong> Best check yo self, you're not looking too good."
    Print "           </div>"
  Endif
  
  Print "           <div class=\"field\">"
  Print "                 <label for=\"email\">"
  Print ("                   Email Address:")
  Print "                 </label>"
  Print "                 <input type=\"text\" id=\"email\" name=\"email\" value=\"\" placeholder=\"Email\" class=\"login\"/>"
  Print "           </div> <!-- /field -->"
  
  If Request.Get["err1"] = "6" Then
    Print "           <div class=\"control-group\">"
    Print "             <label class=\"control-label\">Alerts</label>"
    Print "             <div class=\"controls\">"
    Print "             <div class=\"alert\">"
    Print "             <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>"
    Print "             <strong>Warning!</strong> Bad Email adress"
    Print "           </div>"
  Endif
  
  Print "           <div class=\"field\">"
  Print "                 <label for=\"password\">"
  Print ("                   Password:")
  Print "                 </label>"
  Print "                 <input type=\"password\" id=\"password\" name=\"password\" value=\"\" placeholder=\"Password\" class=\"login\"/>"
  Print "           </div><!-- /field -->"
  
  If Request.Get["err1"] = "4" Then
    Print "           <div class=\"control-group\">"
    Print "             <label class=\"control-label\">Alerts</label>"
    Print "             <div class=\"controls\">"
    Print "             <div class=\"alert\">"
    Print "             <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>"
    Print "             <strong>Warning!</strong> Passwords do not match"
    Print "           </div>"
  Endif
  
  Print "           <div class=\"field\">"
  Print "                 <label for=\"confirm_password\">"
  Print ("                   Confirm Password:")
  Print "                 </label>"
  Print "                 <input type=\"password\" id=\"confirm_password\" name=\"confirm_password\" value=\"\" placeholder=\"Confirm Password\" class=\"login\"/>"
  Print "           </div><!-- /field -->"
  
  If Request.Get["err1"] = "4" Then
    Print "           <div class=\"control-group\">"
    Print "             <label class=\"control-label\">Alerts</label>"
    Print "             <div class=\"controls\">"
    Print "             <div class=\"alert\">"
    Print "             <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>"
    Print "             <strong>Warning!</strong> Passwords do not match"
    Print "           </div>"
  Endif
  
  
  Print "       </div><!-- /login-fields -->"
  Print "       <div class=\"login-actions\">"
  Print "           <span class=\"login-checkbox\">"
  Print "                 <input id=\"Field\" name=\"Accept\" type=\"checkbox\" class=\"field login-checkbox\" value=\"First Choice\" tabindex=\"4\" />"
  Print "                 <label class=\"choice\" for=\"Field\">"
  Print ("                   Agree with the Terms & Conditions.")
  Print "                 </label>"
  Print "           </span>"
  Print "       <button class=\"button btn btn-primary btn-large\">"
  Print ("         Register")
  Print "       </button>"
  Print "       </div><!-- .actions -->"
  
  If Request.Get["err1"] = "1" Then
    Print "           <div class=\"control-group\">"
    Print "             <label class=\"control-label\">Alerts</label>"
    Print "             <div class=\"controls\">"
    Print "             <div class=\"alert\">"
    Print "             <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>"
    Print "             <strong>Warning!</strong> Passwords do not match"
    Print "           </div>"
  Endif
  
  Print "   </form>"
  Print "  </div><!-- /content -->"
  Print " </div><!-- /account-container -->"
  Print "<!-- Text Under Box -->"
  Print "<div class=\"login-extra\">"
  Print ("     Already have an account?")
  Print "<a href=\"inex.r?login\">"
  Print ("Login to your account")
  Print "</a>"
  Print "</div><!-- /login-extra -->"
  Print File.Load("Signup/Footer")
  Response.End
End
