' Gambas module file

' Gambas class file
Public Sub Signup()
  Dim USER_DATA As Collection
  If IsNull(Request.Cookies["__ursa"]) = False Then
      If Exist(Global.WHEREIS_SITE_ROOT & "/Users/" & Request.Cookies["__ursa"] & "") = True Then
          USER_DATA = JSON.Decode(File.Load(Global.WHEREIS_SITE_ROOT & "/Users/" & Request.Cookies["__ursa"] & "/Data.json"))
          If USER_DATA["SECRET_KEY"] = Request.Cookies["__apix"] Then
              Response.Begin
              WLoginnedin.Render

          Else
            WRegister.Render
          Endif
      'Print_Signup()
      Endif
  Else
  WRegister.Render
  Endif
End
